name: sites
channels:
    - defaults
    - conda-forge
dependencies:
  - python=3.12.*
  - xlsxwriter
  - scipy
  - pandas
  - numpy
  - matplotlib
  - openpyxl
  - pyarrow
  - pip
  - conda-forge::gdal
  - conda-forge::exiftool
  - pip:
    - pyexiftool
